# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170902_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌表',
                'db_table': 'restsv_brands',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '型号',
                'verbose_name_plural': '型号表',
                'db_table': 'restsv_models',
            },
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'verbose_name': '配件', 'verbose_name_plural': '配件表'},
        ),
    ]
